name: Bump Version on Push

on:
  push:
    branches:
      - "**"

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Extract current version
        id: extract_version
        run: |
          VERSION=$(grep -oP '__version__ = "\K[0-9]+\.[0-9]+\.[0-9]+' app/routers/__init__.py)
          echo "CURRENT_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Increment version
        id: increment_version
        run: |
          IFS='.' read -r major minor patch <<< "$CURRENT_VERSION"
          MINOR=$((minor + 1))
          NEW_VERSION="$major.$MINOR.$patch"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Update version in __init__.py
        run: |
          sed -i "s/__version__ = \"$CURRENT_VERSION\"/__version__ = \"$NEW_VERSION\"/" app/routers/__init__.py

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Commit and push changes
        env:
          TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add app/routers/__init__.py
          git commit -m "Bump version to $NEW_VERSION"
          git push origin HEAD:${{ github.ref_name }}
